-- MySQL Script generated by MySQL Workbench
-- Fri May  6 14:03:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chubaruk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chubaruk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chubaruk` DEFAULT CHARACTER SET utf8 ;
USE `chubaruk` ;

-- -----------------------------------------------------
-- Table `chubaruk`.`tariffs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`tariffs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tariff` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(6,3) UNSIGNED NOT NULL,
  `interval` VARCHAR(45) NOT NULL DEFAULT '30 day',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`tariff` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`services` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`service` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`contracts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `service_id` INT UNSIGNED NOT NULL,
  `tariff_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contracts_tariffs_id_idx` (`tariff_id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_contracts_service_id_services_id_idx` (`service_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_tariff_id_tariffs_id`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `chubaruk`.`tariffs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contracts_service_id_services_id`
    FOREIGN KEY (`service_id`)
    REFERENCES `chubaruk`.`services` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`identity_docs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`identity_docs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL DEFAULT 'REPUBLIC OF AZERBAIJAN IDENTITY CARD',
  `surname` VARCHAR(45) NOT NULL,
  `given_name` VARCHAR(45) NOT NULL,
  `patronymic_name` VARCHAR(45) NULL,
  `sex` ENUM('male', 'female', 'X') NOT NULL,
  `nationality` VARCHAR(45) NULL DEFAULT 'AZERBAIJAN',
  `date_of_birth` DATE NOT NULL,
  `doc_number` VARCHAR(45) NOT NULL,
  `date_of_expiry` DATE NOT NULL,
  `fin` VARCHAR(7) NULL,
  `can` VARCHAR(24) NULL,
  `date_of_issue` DATE NULL,
  `place_of_birth` VARCHAR(45) NULL,
  `blood_group` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fin_UNIQUE` (`fin` ASC) VISIBLE,
  UNIQUE INDEX `can_UNIQUE` (`can` ASC) VISIBLE,
  UNIQUE INDEX `doc_number_UNIQUE` (`doc_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`contact_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`contact_persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `patronymic_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`phone_numbers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`emails` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`contact_person_phone_numbers_emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`contact_person_phone_numbers_emails` (
  `contact_person_id` INT UNSIGNED NOT NULL,
  `phone_number_id` INT UNSIGNED NULL,
  `email_id` INT UNSIGNED NULL,
  UNIQUE INDEX `phone_number_id_UNIQUE` (`phone_number_id` ASC) VISIBLE,
  UNIQUE INDEX `email_id_UNIQUE` (`email_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_person_id_persons_id`
    FOREIGN KEY (`contact_person_id`)
    REFERENCES `chubaruk`.`contact_persons` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_phone_number_id_phone_numbers_id`
    FOREIGN KEY (`phone_number_id`)
    REFERENCES `chubaruk`.`phone_numbers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_email_id_emails_id`
    FOREIGN KEY (`email_id`)
    REFERENCES `chubaruk`.`emails` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`addresses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `post_index` VARCHAR(20) NULL,
  `country` VARCHAR(45) NULL DEFAULT 'Azerbaijan',
  `city` VARCHAR(45) NOT NULL DEFAULT 'Baku',
  `district` VARCHAR(45) NULL DEFAULT 'Sebail',
  `street` VARCHAR(45) NOT NULL,
  `building` VARCHAR(8) NOT NULL,
  `block` VARCHAR(8) NULL,
  `floor` VARCHAR(6) NULL,
  `apartment` VARCHAR(6) NULL,
  `notes` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`private`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`private` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contact_id` INT UNSIGNED NOT NULL,
  `identity_doc_id` INT UNSIGNED NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_privates_identity_docs_id_idx` (`identity_doc_id` ASC) VISIBLE,
  INDEX `fk_private_contact_id_cppne_contact_person_id_idx` (`contact_id` ASC) VISIBLE,
  INDEX `fk_private_address_id_addresses_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_private_identity_doc_id_identity_docs_id`
    FOREIGN KEY (`identity_doc_id`)
    REFERENCES `chubaruk`.`identity_docs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_private_contact_id_cppne_contact_person_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `chubaruk`.`contact_person_phone_numbers_emails` (`contact_person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_private_address_id_addresses_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `chubaruk`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`companies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address_id` INT UNSIGNED NOT NULL,
  `contact_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_companies_address_id_addresses_id_idx` (`address_id` ASC) VISIBLE,
  INDEX `fk_companies_contact_id_cppne_contact_person_id_idx` (`contact_id` ASC) VISIBLE,
  UNIQUE INDEX `address_id_UNIQUE` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `contact_id_UNIQUE` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `fk_companies_address_id_addresses_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `chubaruk`.`addresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_companies_contact_id_cppne_contact_person_id`
    FOREIGN KEY (`contact_id`)
    REFERENCES `chubaruk`.`contact_person_phone_numbers_emails` (`contact_person_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`subscribers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`subscribers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `contract_id` INT UNSIGNED NOT NULL,
  `private_id` INT UNSIGNED NULL,
  `company_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subscribers_contracts_id_idx` (`contract_id` ASC) VISIBLE,
  INDEX `fk_subscribers_privates_id_idx` (`private_id` ASC) VISIBLE,
  INDEX `fk_subscribers_companies_id_idx` (`company_id` ASC) VISIBLE,
  UNIQUE INDEX `private_id_UNIQUE` (`private_id` ASC) VISIBLE,
  UNIQUE INDEX `company_id_UNIQUE` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscribers_contracts_id`
    FOREIGN KEY (`contract_id`)
    REFERENCES `chubaruk`.`contracts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscribers_privates_id`
    FOREIGN KEY (`private_id`)
    REFERENCES `chubaruk`.`private` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subscribers_companies_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `chubaruk`.`companies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`operators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`operators` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chubaruk`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chubaruk`.`connections` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `service_id` INT UNSIGNED NOT NULL,
  `operator_id` INT UNSIGNED NOT NULL,
  `subscriber_id` INT UNSIGNED NOT NULL,
  `connection_date` DATETIME NOT NULL DEFAULT NOW(),
  `circuit_id` VARCHAR(45) NOT NULL,
  `state` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `connection_operator_fk_idx` (`operator_id` ASC) VISIBLE,
  INDEX `connection_subscriber_fk_idx` (`subscriber_id` ASC) VISIBLE,
  UNIQUE INDEX `circruit_id_UNIQUE` (`circuit_id` ASC) VISIBLE,
  CONSTRAINT `fk_connections_subscribers_id`
    FOREIGN KEY (`subscriber_id`)
    REFERENCES `chubaruk`.`subscribers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_connections_operators_id`
    FOREIGN KEY (`operator_id`)
    REFERENCES `chubaruk`.`operators` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
